name: Build

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container: asciidoctor/docker-asciidoctor
        steps:
            - uses: actions/checkout@v3
            - name: Build course
              run: |
                /bin/bash -x ./scripts/build_course.sh practicum
